import Head from 'next/head'
import { Article } from './Article'

export default function Home() {
  return (
    <div>
      {/* TODO THIS WHOLE HEAD */}
      <Head>
        <title>TODO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <Head>
          <link rel="stylesheet" href="article.css" />
        </Head>
      </Head>

      <Article />
    </div>
  )
}
