import Head from 'next/head'
import { RawWebpage } from './RawWebpage'

export default function Home() {
  return (
    <div>
      {/* TODO THIS WHOLE HEAD */}
      <Head>
        <title>TODO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <RawWebpage />
    </div>
  )
}
